pipeline {
    agent any

    environment {
        DOCKERHUB_USER = "imi1998"
        FRONTEND_IMAGE = "$DOCKERHUB_USER/ott-frontend"
        BACKEND_IMAGE = "$DOCKERHUB_USER/ott-backend"
    }

    stages {

        stage('Checkout') {
            steps {
              git branch: 'main',
                  credentialsId: '33b77918-1570-4050-a0c8-78b1e7eacf47',
                  url: 'https://github.com/imthi-13/sre_team'

              sh 'echo "Workspace content:"'
              sh 'ls -R'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh '''
                docker build -t $FRONTEND_IMAGE:$BUILD_NUMBER frontend/
                docker build -t $BACKEND_IMAGE:$BUILD_NUMBER backend/
                '''
            }
        }

        stage('Push Images') {
            steps {
                sh '''
                echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
                docker push $FRONTEND_IMAGE:$BUILD_NUMBER
                docker push $BACKEND_IMAGE:$BUILD_NUMBER
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                kubectl set image deployment/ott-frontend frontend=$FRONTEND_IMAGE:$BUILD_NUMBER
                kubectl set image deployment/ott-backend backend=$BACKEND_IMAGE:$BUILD_NUMBER
                '''
            }
        }
    }
}
