pipeline {
    agent any

    environment {
        IMAGE = "imi1998/netflix:${BUILD_NUMBER}"
    }

    stages {
        stage('Clone Repo') {
            steps {
              git branch: 'main',
                  credentialsId: '33b77918-1570-4050-a0c8-78b1e7eacf47',
                  url: 'https://github.com/imthi-13/sre_team'

              sh 'echo "Workspace content:"'
              sh 'ls -R'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                cd netflix-project
                docker build -t $IMAGE .
                """
            }
        }

        stage('Push to Registry') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: '5caf6ac4-830c-479e-8440-9c310ec7155a',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh """
                    docker login -u $USER -p $PASS
                    docker push $IMAGE
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-minikube', variable: 'KUBECONFIG_FILE')]) {
                    sh """
                    export KUBECONFIG=$KUBECONFIG_FILE
                    sed -i 's|imi1998/netflix:latest|$IMAGE|g' netflix-project/k8s/deployment.yaml
                    kubectl apply -f netflix-project/k8s/ --validate=false
                    """
            }
        }
    }
}

