pipeline {
  agent any
  environment {
    REGISTRY = "docker.io"                     // or your registry host
    DOCKERHUB_USER = "imi1998"
    IMAGE_REPO = "${DOCKERHUB_USER}/devops-app"
    IMAGE_TAG = "${env.BUILD_NUMBER}"
  }
  stages {
    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: '33b77918-1570-4050-a0c8-78b1e7eacf47',
            url: 'https://github.com/imthi-13/sre_team'

        sh 'echo "Workspace content:"'
        sh 'ls -R'
      }
    }
    stage('Build Image') {
      steps {
        dir('second_project/app') {
          sh "docker build -t ${IMAGE_REPO}:${IMAGE_TAG} ."
        }
      }
    }
    stage('Unit Test') {
      steps {
        echo "Run minimal test step (add pytest or npm test if present)"
        sh "echo run tests here || true"
      }
    }
    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: '5caf6ac4-830c-479e-8440-9c310ec7155a', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin ${REGISTRY}"
          sh "docker push ${IMAGE_REPO}:${IMAGE_TAG}"
        }
      }
    }
    stage('Deploy to k8s') {
      steps {
         withKubeConfig(credentialsId: 'kubeconfig') {
            sh '''
            kubectl apply -f second_project/k8s/namespace.yaml
            kubectl apply -f second_project/k8s/configmap.yaml
            kubectl apply -f second_project/k8s/service.yaml
            kubectl apply -f second_project/k8s/deployment.yaml
            kubectl apply -f second_project/k8s/ingress.yaml
            '''
        }
      }
    }
  }
  post {
    success {
      echo "Pipeline completed successfully. Image: ${IMAGE_REPO}:${IMAGE_TAG}"
    }
    failure {
      echo "Pipeline failed. Check logs."
    }
  }
}

